### ISSUE TITLE
[Bug] Xcode 15 빌드 에러

### ISSUE THREAD

**Issue by yeonju0110** [teamOpener/OpenOff-Client#149]
### - 오류명
1. No template named 'unary_function' in namespace 'std'; did you mean '__unary_function'?
2. Thread 1: signal SIGABRT

### - 오류설명

![image](https://github.com/teamOpener/OpenOff-Client/assets/97719273/65be2896-43f0-4945-8270-2a0d567eaf03)
![image](https://github.com/teamOpener/OpenOff-Client/assets/97719273/b0ea29fd-f2a1-471c-b00b-ebcaccdb1c7b)

### - OS Type
-  ios

**Comment by suhailrifkykramphub** [comment]
I got this issue too and it was solved when I applied the fix auto suggested by Xcode
